config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "homes#top"
  get 'home/about' => 'homes#about', as: 'about'

  resources :books, only: [:create,:show,:index,:edit,:update,:destroy]
  resources :users, only: [:create,:show,:index,:edit,:update]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :books, dependent: :destroy
  validates :name, uniqueness: true
  validates :name,length:{minimum:2,maximum:20}
  validates :introduction,
    length:{ maximum:50}



  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  def create
    super
    flash[:notice] = "Signed in successfully."

  end


  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = User.find(params[:id])
    @books = Book.all
    @book = Book.new
    @book_list = @user.books
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to user_path(current_user.id)
    else
      render '/books'
    end
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
    @user = User.find(current_user.id)

  end

  def update
    @user = User.find(current_user.id)
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:introduction,:profile_image)
  end

  def book_params
    params.require(:book).permit(:title,:body)
  end

  def is_matching_login_user
    user =User.find(params[:id])
    unless user.id == current_user.id
      redirect_to post_images_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-lg-6 mx-auto mt-3">
        <h2>User info</h2>
        <% if @user.errors.any?%>
          <h2>
            <%= @user.errors.count %>error prohibited this obj from being saved:
          </h2>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
        <%= form_with model: @user do |f| %>
          <label>Name</label>
          <%= f.text_field :name, autofocus: true, class: 'w-100 mb-3' %>
          <label>Image</label>
          <%= f.file_field :profile_image, placeholder:"ファイルを選択", accept: "image/*",class: 'w-100 mb-3' %>
          <label>Introduction</label>
          <%= f.text_area :introduction ,class: 'w-100 mb-3' %>
          <%= f.submit "Update User",class: 'btn btn-secondary' %>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<main>
  <p id="notice"></p>
    <div class="container px-5 px-sm-0">
    <div class="row">
        <%= render 'layouts/profile', user: @user ,book: @book %>
      <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td class="col-md-3">
                  <% if user.profile_image.attached? %>
                    <%= image_tag user.profile_image, size: "80x80" %>
                  <% else %>
                    <%= image_tag 'no_image', size: "80x80" %>
                  <% end %>
                </td>
                <td class="col-md-3"><span><%= user.name %></span></td>
                <td class="col-md-2"><span><%= link_to user_path(user) do %>Show<% end %></span></td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <p id="notice"></p>
  <% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <div>
         <%= image_tag @user.get_profile_image(100,100) %>
        </div>
        <table class="table">
          <thead>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <td>Introduction</td>
              <td class="table-borderless"><%= @user.introduction %></td>
            </tr>
          </thead>
        </table>
        <%= link_to edit_user_path , class: 'btn btn-outline-dark w-100 mb-3' do %><i class="fas fa-user-cog "></i><% end %>
        <div>
          <%= form_with model: @book do |f| %>
            <h1>New book</h1>
            <label>Title</label>
            <%= f.text_field :title , class: "w-100 mb-3" %>
            <label>Opinion</label>
            <%= f.text_area :body , class: "w-100 mb-3" %>
            <%= f.submit "Create Book",class: 'btn btn-success rounded text-white'%>
          <% end %>
        </div>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table">
          <thead>
            <tr>
              <th></th>
              <th class="book-title">Title</th>
              <th class="book-body">Opinion</th>
            </tr>
          </thead>
          <tbody>
            <% @book_list.each do |book| %>
              <tr>
                <td class="col-lg-1">
                  <%= link_to image_tag(book.user.get_profile_image(80,80)), user_path(book.user.id) %>
                </td>
                <td class="col-lg-3">
                  <%= link_to book_path(book) do %>
                  <span><%= book.title %></span>
                  <% end %></td>
                </td>
                <td class="col-lg-4"><span><%= book.body %></span></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>