config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "homes#top"
  get 'home/about' => 'homes#about', as: 'about'

  resources :books, only: [:create,:show,:index,:edit,:update,:destroy]
  resources :users, only: [:create,:show,:index,:edit,:update]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: {minimum:0 ,maximum:200}


  belongs_to :user


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = User.find(@book.user_id)
  end

  def create
    @books = Book.all
    @user = User.find(current_user.id)
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def edit
    book = Book.find(params[:id])
    unless book.user.id == current_user.id
      redirect_to books_path
    end
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end


  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end


  private

  def user_params
    params.require(:user).permit(:name,:introduction,:profile_image)
  end

  def book_params
    params.require(:book).permit(:title,:body)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-lg-6 mx-auto mt-3">
        <h1>Editing Book</h1>
          <% if @book.errors.any? %>
            <h3>
              <%= @book.errors.count %>errors prohibited this obj from being saved:
            </h3>
            <ul>
              <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
              <% end %>
          <% end %>
          <%= form_with model: @book do |f| %>
            <label>Name</label>
            <%= f.text_field :title, autofocus: true, class: 'w-100 mb-3' %>
            <label>Opinion</label>
            <%= f.text_area :body ,class: 'w-100 mb-3' %>
            <%= f.submit "Update Book",class: 'btn btn-success rounded text-white mb-3' %>
          <% end %>

        <%= link_to "Show", book_path(current_user)%> | <%= link_to "Back", books_path %>
      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<main>
  <p id="notice"></p>
  <div class="container px-5 px-sm-0">
    <% if @book.errors.any? %>
        <h3>
          <%= @book.errors.count %>errors prohibited this obj from being saved:
        </h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    <div class="row">
      <%= render 'layouts/profile', user: @user ,book: @book %>
      <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table">
          <thead>
            <tr>
              <th class="col-md-1"></th>
              <th class="col-md-2">Title</th>
              <th class="col-md-5">Opinion</th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td class="col-md-1">
                  <%= link_to image_tag(book.user.get_profile_image(80,80)), user_path(book.user.id) %>
                </td>
                <td class="col-md-2">
                  <%= link_to book_path(book) do %>
                  <span><%= book.title %></span>
                  <% end %>
                </td>
                <td class="col-md-5"><span><%= book.body %></span></td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
</main>

app/views/books/show.html.erb
<main>
<p id="notice"></p>
  <% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <div>
        <%= image_tag @book.user.get_profile_image(100,100) %>
        </div>
        <table class="table">
          <thead>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <td>Introduction</td>
              <td class="table-borderless"><%= @user.introduction %></td>
            </tr>
          </thead>
        </table>
        <%= link_to edit_user_path , class: 'btn btn-outline-dark w-100 mb-3' do %><i class="fas fa-user-cog "></i><% end %>
        <div>
          <%= form_with model: @book_new do |f| %>
            <h1>New book</h1>
            <label>Title</label>
            <%= f.text_field :title , class: "w-100 mb-3" %>
            <label>Opinion</label>
            <%= f.text_area :body , class: "w-100 mb-3" %>
            <%= f.submit "Create Book", class: 'btn btn-success rounded text-white'%>
          <% end %>
        </div>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table">
          <tbody>
              <tr>
                <% if @book.user == current_user %>
                  <td class="col-md-1">
                    <%= link_to image_tag(@book.user.get_profile_image(100,100)), user_path(@book.user.id) %>
                    <br>
                    <%= link_to user_path(@book.user.id) do%><%= @book.user.name %><% end %>
                  </td>
                  <td class="col-md-2">
                    <%= link_to book_path(@book) do %>
                      <%= @book.title %>
                    <% end %>
                  </td>
                  <td class="col-md-3"><%= @book.body %></td>
                  <td class="col-md-1"><%= link_to "Edit" ,edit_book_path(@book.id), class: 'btn btn-success rounded text-white' %></td>
                  <td class="col-md-1"><%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に削除しますか？" ,class: 'btn btn-danger rounded text-white' %></td>
                <% else %>
                  <td class="col-md-5">
                    <%= link_to image_tag(@book.user.get_profile_image(100,100)), user_path(@book.user.id) %>
                    <br>
                    <%= link_to user_path(@book.user.id) do%><%= @book.user.name %><% end %>
                  </td>
                  <td class="col-md-1">
                    <%= link_to book_path(@book) do %>
                      <%= @book.title %>
                    <% end %>
                  </td>
                  <td class="col-md-2"><%= @book.body %></td>
                <% end %>
              </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>