config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "homes#top"
  get 'home/about' => 'homes#about', as: 'about'

  resources :books, only: [:create,:show,:index,:edit,:update,:destroy]
  resources :users, only: [:create,:show,:index,:edit,:update]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_notifications.html.erb
<div>
  <%= flash[:notice] %>
</div>

app/views/layouts/_profile.html.erb
<div class="col-md-3">
  <h2>User info</h2>
    <div>
     <%= image_tag current_user.get_profile_image(100,100) %>
    </div>
    <table class="table">
    <thead>
      <tr>
        <th>name</th>
        <th><%= current_user.name %></th>
      </tr>
      <tr>
        <td>Introduction</td>
         <td class="table-borderless"><%= current_user.introduction %></td>
      </tr>
    </thead>
  </table>
  <div class="row">
    <%= link_to edit_user_path((current_user.id)) , class: 'btn btn-outline-dark w-75 mx-auto mb-3' do %><i class="fas fa-user-cog "></i><% end %>
  </div>
    <div>
    <%= form_with model: book do |f| %>
      <h1>New book</h1>
      <label>Title</label>
      <%= f.text_field :title , class: "w-100 mb-3" %>
      <label>Opinion</label>
      <%= f.text_area :body , class: "w-100 mb-3" %>
      <%= f.submit "Create Book", class: 'btn btn-success rounded text-white'%>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/5f8827088c.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark p-0">
        <div class="container">
          <% if user_signed_in? %>
          <%= link_to root_path, class: 'navbar-brand small ' do %>
            Bookers
          <% end %>
          <div class="collapse navbar-collapse" >
            <ul class="nav-bar-nav ml-auto list-unstyled list-inline text-white">
              <li class="nav-item list-inline-item">
                <%= link_to user_path(current_user.id), class: 'nav-link  text-white ' do %>
                 <i class="fas fa-home"></i> Home
                <% end %>
              </li>
              <li class="nav-item list-inline-item">
                <%= link_to users_path, class: 'nav-link  text-white' do %>
                  <i class="fas fa-users"></i> Users
                <% end %>
              </li>
              <li class="nav-item list-inline-item">
                <%= link_to books_path, class: 'nav-link  text-white' do %>
                  <i class="fas fa-book-open"></i> Books
                <% end %>
              </li>
              <li class="nav-item list-inline-item">
                <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link  text-white' do %>
                <i class="fas fa-sign-out-alt"></i> Log out
                <% end %>
              </li>
            </ul>
          </div>
        <% else %>
          <a class="navbar-brand small" href="/"><span>Bookers</span></a>
          <div class="collapse navbar-collapse" >
            <ul class="nav-bar-nav ml-auto list-unstyled list-inline text-white">
                <li class="nav-item list-inline-item">
                  <%= link_to root_path, class: 'nav-link  text-white' do %>
                    <i class="fas fa-home"></i> Home
                  <% end %>
                </li>
                <li class="nav-item list-inline-item">
                  <%= link_to about_path, class: 'nav-link  text-white' do %>
                    <i class="fas fa-link"></i> About
                  <% end %>
                </li>
                <li class="nav-item list-inline-item">
                  <%= link_to new_user_registration_path, class: 'nav-link  text-white' do %>
                    <i class="fas fa-user-plus"></i> Sign up
                  <% end %>
                </li>
                <li class="nav-item list-inline-item">
                  <%= link_to new_user_session_path, class: 'nav-link  text-white' do %>
                    <i class="fas fa-sign-in-alt"></i> Log in
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= render 'layouts/notifications' %>
    <%= yield %>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>

    </footer>
    </body>
</html>